name: Frontend Application CI/CD

on:
  push:
    branches: [main, develop, sqe, preprod, qa]
    tags: ['v*']
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - sqe
        - qa
        - pre-production
        - production
      skip-deployment:
        description: 'Skip deployment (build only)'
        required: false
        default: false
        type: boolean


jobs:
  call-shared-workflow:
    uses: YOUR_ORG/shared-ci-cd-workflows/.github/workflows/shared-ci-cd.yml@main
    with:
      # Environment configuration
      environment: ${{ github.event.inputs.environment || 'development' }}
      
      # Deployment controls
      skip-deployment: ${{ github.event.inputs.skip-deployment || false }}
      
      # App-specific configuration (customize for your frontend app)
      app-location: '/'                    # Change to your source code location (e.g., 'frontend', 'client', 'app')
      output-location: 'build'             # Change to your build output directory (e.g., 'dist', 'public', 'www')
      
      # All other configuration (security, quality gates) is centralized in the shared workflow
    
    secrets:
      # Generic Azure Static Web Apps API token (resolved per environment via environment-level secrets)
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      
      # Security scanning secrets (set these in your frontend repo)
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CHECKMARX_CLIENT_ID: ${{ secrets.CHECKMARX_CLIENT_ID }}
      CHECKMARX_SECRET: ${{ secrets.CHECKMARX_SECRET }}
      CHECKMARX_TENANT: ${{ secrets.CHECKMARX_TENANT }}
      CHECKMARX_BASE_URI: ${{ secrets.CHECKMARX_BASE_URI }}