name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
        - development
        - staging
        - qa
        - pre-production
        - production
      target_version:
        description: 'Version to rollback to (optional - uses last successful if empty)'
        required: false
        type: string
      reason:
        description: 'Reason for rollback'
        required: true
        type: string

jobs:
  rollback:
    uses: YOUR_ORG/shared-ci-cd-workflows/.github/workflows/manual-rollback.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      target_version: ${{ github.event.inputs.target_version }}
      reason: ${{ github.event.inputs.reason }}
      
      # App-specific configuration (must match your CI/CD workflow settings)
      app-location: '/'                    # Change to match your source code location
      output-location: 'build'             # Change to match your build output directory
    secrets:
      # Generic Azure Static Web Apps API token (resolved per environment via environment-level secrets)
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      
      # GitHub token for repository access and deployment tracking
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}