name: Frontend CI/CD with Artifactory

on:
  push:
    branches: [main, develop, sqe, preprod, qa]
    tags: ['v*']
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - sqe
        - qa
        - pre-production
        - production

jobs:
  ci-cd:
    uses: YOUR_ORG/shared-ci-cd-workflows/.github/workflows/shared-ci-cd-artifactory.yml@main
    with:
      environment: ${{ github.event.inputs.environment || 'development' }}
      app-location: '/'
      output-location: 'build'
      app-name: 'YOUR_APP_NAME'
    
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CHECKMARX_CLIENT_ID: ${{ secrets.CHECKMARX_CLIENT_ID }}
      CHECKMARX_SECRET: ${{ secrets.CHECKMARX_SECRET }}
      CHECKMARX_TENANT: ${{ secrets.CHECKMARX_TENANT }}
      CHECKMARX_BASE_URI: ${{ secrets.CHECKMARX_BASE_URI }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}